### PR TITLE
ISSITES-5840 Public Sites Search Bar

### PR DESCRIPTION
**Pull request by liaoethan**

### CODE REVIEW

**Comment by jotchon** [comment]
Hi @liaoethan, it is coming along well!  I had a few questions about how it should work...
- Should i see any search results when typing into the search bar?
- Are you done with all the styles?  it seems to missing some that I noted in the image attached.
- Should I see the search results button at all times?  Or only after typing?
- Should the popular search buttons have default links?
- "Popular" and "Suggested" are not localizable

search

Hope this is helpful!  Let me know if you have any questions!

**Comment by liaoethan** [comment]
Hi @jotchon,

Thanks for the feedback! The search results should show up now after creating a Search Blueprint in _Control Panel -> Search Experiences_, then adding the ID to the new search blueprint ID configuration on the master page with the public sites nav. I made changes to most of the styles. For the z-index issue, the fix from the other ticket will also apply here. For the "Popular" and "Suggested" buttons, they're localized with the freemarker with _languageUtil_. Other than those, I made the other changes that you specified.

Note: When setting up the search blueprint, after creating the blueprint, go to Query Builder -> Query Settings and under the Searchable Types section, select "Selected Types" and filter out Pages only.

ALSO another Note: Make sure to start up an environment that uses U36+ or it won't have the Search Experiences.

**Comment by jotchon** [comment]
Hi @liaoethan, 

It looks great with your changes!  I found some other things to mention while testing...
1. When hovering on the search icon, the cursor is not a pointer (white glove), but a black arrow.
2. The "See All Results" button still shows before writing anything in the search input and when the search input is empty.  The button shouldn't show at all in these cases.
3. Also if there are no search results, it should show a message saying "There are no results" without the "See All Results" button.  Currently on LRDC, it suggests a term with a link in case the word is misspelled.  Not sure if that's necessary.
4. Are mobile styles included in this ticket?

Could you also write out those steps for setting up search blueprint on the ticket?  Seems like valuable info that will need to be shared with another reviewer.  Thanks!

Let me know if you have any questions!

**Comment by liaoethan** [comment]
Hi @jotchon! I made changes to your feedback and rebased / fixed merge conflicts - the new pull is here:
https://github.com/jotchon/liferay-portal/pull/8

The only thing I didn't add was the word misspell correction since that was a swiftype functionality that we will no longer have. Other than that, I refined the mobile styling, the search icon change, and the _See All Results_ button is now consistent.

Let me know if I need to make any additional changes! Thanks again!

**Pull request closed without merging**
